INSERT INTO public.nationalities (name) VALUES
	 ('Afghanistan'),
	 ('Albania'),
	 ('Algeria'),
	 ('Andorra'),
	 ('Angola'),
	 ('Antigua and Barbuda'),
	 ('Argentina'),
	 ('Armenia'),
	 ('Australia'),
	 ('Austria');
INSERT INTO public.nationalities (name) VALUES
	 ('Azerbaijan'),
	 ('Bahamas'),
	 ('Bahrain'),
	 ('Bangladesh'),
	 ('Barbados'),
	 ('Belarus'),
	 ('Belgium'),
	 ('Belize'),
	 ('Benin'),
	 ('Bhutan');
INSERT INTO public.nationalities (name) VALUES
	 ('Bolivia'),
	 ('Bosnia and Herzegovina'),
	 ('Botswana'),
	 ('Brazil'),
	 ('Brunei'),
	 ('Bulgaria'),
	 ('Burkina Faso'),
	 ('Burundi'),
	 ('Cabo Verde'),
	 ('Cambodia');
INSERT INTO public.nationalities (name) VALUES
	 ('Cameroon'),
	 ('Canada'),
	 ('Central African Republic'),
	 ('Chad'),
	 ('Chile'),
	 ('China'),
	 ('Colombia'),
	 ('Comoros'),
	 ('Congo (Congo-Brazzaville)'),
	 ('Costa Rica');
INSERT INTO public.nationalities (name) VALUES
	 ('Croatia'),
	 ('Cuba'),
	 ('Cyprus'),
	 ('Czech Republic'),
	 ('Democratic Republic of the Congo'),
	 ('Denmark'),
	 ('Djibouti'),
	 ('Dominica'),
	 ('Dominican Republic'),
	 ('Ecuador');
INSERT INTO public.nationalities (name) VALUES
	 ('Egypt'),
	 ('El Salvador'),
	 ('Equatorial Guinea'),
	 ('Eritrea'),
	 ('Estonia'),
	 ('Eswatini (fmr. Swaziland)'),
	 ('Ethiopia'),
	 ('Fiji'),
	 ('Finland'),
	 ('France');
INSERT INTO public.nationalities (name) VALUES
	 ('Gabon'),
	 ('Gambia'),
	 ('Georgia'),
	 ('Germany'),
	 ('Ghana'),
	 ('Greece'),
	 ('Grenada'),
	 ('Guatemala'),
	 ('Guinea'),
	 ('Guinea-Bissau');
INSERT INTO public.nationalities (name) VALUES
	 ('Guyana'),
	 ('Haiti'),
	 ('Honduras'),
	 ('Hungary'),
	 ('Iceland'),
	 ('India'),
	 ('Indonesia'),
	 ('Iran'),
	 ('Iraq'),
	 ('Ireland');
INSERT INTO public.nationalities (name) VALUES
	 ('Israel'),
	 ('Italy'),
	 ('Jamaica'),
	 ('Japan'),
	 ('Jordan'),
	 ('Kazakhstan'),
	 ('Kenya'),
	 ('Kiribati'),
	 ('Kuwait'),
	 ('Kyrgyzstan');
INSERT INTO public.nationalities (name) VALUES
	 ('Laos'),
	 ('Latvia'),
	 ('Lebanon'),
	 ('Lesotho'),
	 ('Liberia'),
	 ('Libya'),
	 ('Liechtenstein'),
	 ('Lithuania'),
	 ('Luxembourg'),
	 ('Madagascar');
INSERT INTO public.nationalities (name) VALUES
	 ('Malawi'),
	 ('Malaysia'),
	 ('Maldives'),
	 ('Mali'),
	 ('Malta'),
	 ('Marshall Islands'),
	 ('Mauritania'),
	 ('Mauritius'),
	 ('Mexico'),
	 ('Micronesia');
INSERT INTO public.nationalities (name) VALUES
	 ('Moldova'),
	 ('Monaco'),
	 ('Mongolia'),
	 ('Montenegro'),
	 ('Morocco'),
	 ('Mozambique'),
	 ('Myanmar (Burma)'),
	 ('Namibia'),
	 ('Nauru'),
	 ('Nepal');
INSERT INTO public.nationalities (name) VALUES
	 ('Netherlands'),
	 ('New Zealand'),
	 ('Nicaragua'),
	 ('Niger'),
	 ('Nigeria'),
	 ('North Korea'),
	 ('North Macedonia'),
	 ('Norway'),
	 ('Oman'),
	 ('Pakistan');
INSERT INTO public.nationalities (name) VALUES
	 ('Palau'),
	 ('Palestine'),
	 ('Panama'),
	 ('Papua New Guinea'),
	 ('Paraguay'),
	 ('Peru'),
	 ('Philippines'),
	 ('Poland'),
	 ('Portugal'),
	 ('Qatar');
INSERT INTO public.nationalities (name) VALUES
	 ('Romania'),
	 ('Russia'),
	 ('Rwanda'),
	 ('Saint Kitts and Nevis'),
	 ('Saint Lucia'),
	 ('Saint Vincent and the Grenadines'),
	 ('Samoa'),
	 ('San Marino'),
	 ('Sao Tome and Principe'),
	 ('Saudi Arabia');
INSERT INTO public.nationalities (name) VALUES
	 ('Senegal'),
	 ('Serbia'),
	 ('Seychelles'),
	 ('Sierra Leone'),
	 ('Singapore'),
	 ('Slovakia'),
	 ('Slovenia'),
	 ('Solomon Islands'),
	 ('Somalia'),
	 ('South Africa');
INSERT INTO public.nationalities (name) VALUES
	 ('South Korea'),
	 ('South Sudan'),
	 ('Spain'),
	 ('Sri Lanka'),
	 ('Sudan'),
	 ('Suriname'),
	 ('Sweden'),
	 ('Switzerland'),
	 ('Syria'),
	 ('Tajikistan');
INSERT INTO public.nationalities (name) VALUES
	 ('Tanzania'),
	 ('Thailand'),
	 ('Timor-Leste'),
	 ('Togo'),
	 ('Tonga'),
	 ('Trinidad and Tobago'),
	 ('Tunisia'),
	 ('Turkey'),
	 ('Turkmenistan'),
	 ('Tuvalu');
INSERT INTO public.nationalities (name) VALUES
	 ('Uganda'),
	 ('Ukraine'),
	 ('United Arab Emirates'),
	 ('United Kingdom'),
	 ('United States'),
	 ('Uruguay'),
	 ('Uzbekistan'),
	 ('Vanuatu'),
	 ('Vatican City'),
	 ('Venezuela');
INSERT INTO public.nationalities (name) VALUES
	 ('Vietnam'),
	 ('Yemen'),
	 ('Zambia'),
	 ('Zimbabwe');
